apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkaja-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkaja-chatbot
  template:
    metadata:
      labels:
        app: linkaja-chatbot
    spec:
      containers:
      - name: linkaja-chatbot
        image: your-docker-repo/linkaja-chatbot:latest
        ports:
        - containerPort: 8501
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: linkaja-secrets
              key: GOOGLE_API_KEY